#!/usr/bin/env python3

import os
import sys
import helpers

from twython import Twython
from twython import TwythonAuthError, TwythonError, TwythonRateLimitError
from termcolor import colored
from analyzer import Analyzer

def main():

    #make sure there is only one command-line argument
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets screen_name")

    #get user most recent 50 tweets
    tweets = helpers.get_user_timeline(sys.argv[1], count = 50)

    #absolute path to list
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    #load the above two data set in memory
    analyzer = Analyzer(positives, negatives)

    count = 0

    #for each tweet analyze sentiment
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(score, "green"), colored(tweet, "green"))
        elif score < 0.00:
            print(colored(score, "red"), colored(tweet, "red"))
        else:
            print(colored(score, "yellow"), colored(tweet, "yellow"))
        count += 1
    print(count)

if __name__=="__main__":
    main()
